server.servlet.context-path=/
# PostgreSQL
spring.datasource.write.jdbc-url=jdbc:postgresql://localhost:5432/cambios_db
spring.datasource.write.username=postgres
spring.datasource.write.password=password
spring.datasource.write.driver-class-name=org.postgresql.Driver
spring.datasource.read.jdbc-url=jdbc:postgresql://localhost:5432/cambios_db
spring.datasource.read.username=postgres
spring.datasource.read.password=password
spring.datasource.read.driver-class-name=org.postgresql.Driver
