# PostgreSQL
spring.datasource.write.jdbc-url=jdbc:postgresql://${WRITE_SERVER}/cambios_db
spring.datasource.write.username=${USERNAME_WRITE_DB}
spring.datasource.write.password=${PASSWORD_WRITE_DB}
spring.datasource.write.driver-class-name=org.postgresql.Driver
spring.datasource.read.jdbc-url=jdbc:postgresql://${READ_SERVER}/cambios_db
spring.datasource.read.username=${USERNAME_READ_DB}
spring.datasource.read.password=${PASSWORD_READ_DB}
spring.datasource.read.driver-class-name=org.postgresql.Driver
