server.port=8109
spring.profiles.default=local
spring.application.name=microservicio-cambios
# ====== EUREKA ================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
# ========== JIRA CONFIGURATION ==========
jira.url=https://utp-team-gestion-cambios.atlassian.net
jira.username=U22238193@utp.edu.pe
jira.token=ATATT3xFfGF0LDYVq6vVZzD9ovroom6wWjde989T327qtFsgCvK3_QRpqLbKHtrFCjeSq_FYs3hItwyyg70PCLdR4Ejm9jSb2o18Lh9QOEEc-ygQuNC4gSarKlo2EVDBFolmIO7E28oK9Fe59_YF730XFbo2AWghAH2GRHaTcgskWrFok5ocdvY=C24FCD02
jira.project.key=KAN
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# ========== LOGGING ==========
logging.level.com.microservicio.cambio=DEBUG
# =============== DESHABILITAR EUREKA PARA PRUEBAS ===============
# Estos microservicios usan JIRA en todo momento, no hay sentido en crear un perfil especial para ellos
