server.port=8109
spring.profiles.default=local
spring.application.name=microservicio-cambios
# ====== EUREKA ================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
# ========== JIRA CONFIGURATION ==========
jira.url=https://utp-team-gestion-cambios.atlassian.net
jira.username=U22238193@utp.edu.pe
jira.token=ATATT3xFfGF0F3yIq0JtbAaWhCh_tyBiYyyk3Lf3JWsSJBZvfN7NeR_dh01Pfr8QXiYQaxfqzB8kffyYSdsuUQoihybYY6jAXakj8xS5FsiJWsD2t9MIT79xVLt00kgXFN3ZTGFy1r-JyU9_YvkJmWpvs3sHvUmUcmFwNx2VPb1_ojMJVS-KJeU=30D279D0
jira.project.key=KAN
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# ========== LOGGING ==========
logging.level.com.microservicio.cambio=DEBUG
# =============== DESHABILITAR EUREKA PARA PRUEBAS ===============
# Estos microservicios usan JIRA en todo momento, no hay sentido en crear un perfil especial para ellos
