#I'M GOING TO SKIN ALIVE THE GUY WHO DECIDED TO MAKE THE ACCENTS THROW AN ERROR FOR "MALFORMED INPUT"
spring.application.name=microservicio-users
server.port=${PORT:8221}
server.servlet.context-path=/
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/users_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Eureka
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8762/eureka
eureka.instance.instance-id=${spring.application.name}:${server.port}
# jwt.secret=${JWT_SECRET:3KTMZ7An77+TnowBQVy0+Nop3ADuwmIIbcTszYkOAYY=}
# jwt.expiration=${JWT_EXPIRATION:86400000}

# Logging
management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.show-details=always
logging.file.name=/var/log/restaurante-gestion/user.log
logging.pattern.file="%d %-5level [%thread] %logger - %msg%n"
