server.port=${PORT:8081}
spring.application.name=microservicio-solicitudes
#eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8762}/eureka
eureka.instance.instance-id=${spring.application.name}:${server.port}
# ========== JIRA CONFIGURATION ==========
jira.url=https://utp-restaurante.atlassian.net
jira.username=U21318614@utp.edu.pe
jira.token=ATATT3xFfGF01etw0lT8Iw5k1RbMqpx9nD8VbswUDj7WzMvqOJ5q6IDgCzAqnt5yEfOCdzPIBAcJCyAkz_AplRP_2qKUbdp2Ircsv6LeYdZu2GACi7cgLpjSTo7ksEuhXl_E1-kDouLcnh7Mspehvh1DDLQ-5HdQFpgUDUvtRkxMqydPbfw-NOk=8A277E7D
jira.project.key=SOLICITUD

# ========== DATABASE CONFIGURATION ==========
spring.datasource.url=jdbc:postgresql://${WRITE_SERVER:localhost:5432}/solicitudes_db
spring.datasource.username=${USERNAME_WRITE_DB:postgres}
spring.datasource.password=${PASSWORD_WRITE_DB:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========== LOGGING ==========
logging.level.com.microservicio.solicitudes=DEBUG

#Prometheus
management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.show-details=always
#Logging
logging.file.name=/var/log/restaurante-gestion/solicitudes.log
logging.pattern.file="%d %-5level [%thread] %logger - %msg%n"
